@startuml

!include ./user_event_base.puml

class UserPasswordChangedEvent extends UserEventBase {
    + ChangedAt: DateTime
    + IPAddress: string
}

note top of UserPasswordChangedEvent
    Возникает при смене пароля.
end note

@enduml