@startuml

class SecurityInfo extends ValueObject {
    + PasswordHash: string
    + PasswordChangedAt: DateTime
    + LastFailedAttempt: DateTime?
    + FailedAttemptsCount: int
    + Salt: string
}

@enduml